### PR TITLE
Added sample playbooks and docs for zhmc collection

### PR DESCRIPTION
**Pull request by andy-maier**
See commit message for details.

### CODE REVIEW

**Review by asifmahmud — DISMISSED** [review]
Hi @andy-maier. The sample playbooks look good to me. You should update the main README to include a link to the samples in the `index` section. Once that is done, would be happy to approve!

**Comment by andy-maier** [comment]
@asifmahmud Hi Asif. Which README file are you referring to?
* In the main README of the repo, I don't know where to add a link. It describes a certain structure that the zhmc subtree does not confirm to.
* The zhmc subtree does not contain a README file at this point. Are you asking to create one?

**Comment by asifmahmud** [comment]
@andy-maier I was referring to the main README of the repo. I know it doesn't conform to the structure specified in the readme and it wouldn't be a good idea to link every single playbook there since there is a lot, but one option would be to link the `playbooks` directory under `topics` section (which has been recently renamed from `index`).

**Comment by ddimatos** [comment]
Since zHMC doc is pointing to these playbooks, they may want to test their doc, I think its a fair ask to merge the PR and not link anything from the project README till they release to Galaxy. At that time we can revisit adding a top level topic point to zHMC playbooks. I had briefed you on this @asifmahmud earlier today so I will go ahead and merge.

**Review by ddimatos — APPROVED** [review]
Thanks @andy-maier , I am excited to see the additions and looking forward to the coming collection. Thanks @asifmahmud for the initial review, this was a big help.

**Comment by ddimatos** [comment]
I am overriding the change requested @asifmahmud for now, we can work with them in the coming weeks to get the playbooks tied into the main readme, we can initiate that change and look for @andy-maier feedback.

**Pull request merged**
