### PR TITLE
Reorganization and adding content

### PR DESCRIPTION
**Pull request by ddimatos**
Reorganization and adding content
- This pull request reorganizes the README, adds new topics, content and organizes existing content into topic folders. 
- It also removes all previously stored media files to reduce the size of the latest repository (clone still incurs the historical content and size) and links to the new media center.
- Lastly, it address git issue #44 .
- Also updates the collections/requirements.txt `ibm_zos_core` dependency to version `1.3.0-beta.2`, thus if your Ansible Tower project is enabled to **UPDATE REVISION ON LAUNCH** the latest `ibm_zos_core` of  `1.3.0-beta.2` collection will be pulled by Ansible tower which has different ZOAU dependencies over the prior `ibm_zos_core` version of `v1.2.1`, more on this [here](https://docs.ansible.com/ansible-tower/latest/html/userguide/projects.html)

### CODE REVIEW

**Comment by ddimatos** [comment]
This pull request will be taken out of **Draft** mode and upon review merged in on 3/25/2021

**Comment by ind1go** [comment]
Just a note that the video removals only affect the download size of the repo zip. Cloning the repo will still have them in the history. Not a lot we can do about that without rewriting history and force-pushing which may be destructive for contributors.

**Comment by ddimatos** [comment]
@ind1go - you are correct and good to point out for others. If we were only a few commits in past the media I would be open to rewriting history but at this point we have over 80 commits since then, so it is to destructive now and also unsure how others are using the media files at this point.

**Comment by ddimatos** [comment]
Updated the description per @ind1go 's comment about download size.

**Review by RadhaV2020 — APPROVED** [review]

**Comment by ind1go** [comment]
Looks 👌  😄

**Pull request merged**
