### PR TITLE
Add provisioning for wazi env

### PR DESCRIPTION
**Pull request by adn1107**
I squashed the commit history so we have 1 single clean commit. Let me know you see any issues.

### CODE REVIEW

**Comment by steph-lieu** [comment]
Done testing the PR by reviewing the env variables and running ims-prov and de-prov on wazi

**Comment by ddimatos** [comment]
@adn1107 - I am not sure who from your team you want to review this, but currently the PR has no reviewer and only 1 of 3 checks have passed, linting can't run till your branch is up to date which is one of the 1 errors reported.

image

**Comment by adn1107** [comment]
@ddimatos the PR has been opened for too long. I need to rework it to make it up to date so I convert to to Draft for now.

**Comment by ddimatos** [comment]
No problem, for some reason I thought it was a recent PR. Thank you.

**Pull request closed without merging**
