### PR TITLE
[cloud_infra_center] Update availability_zone description in README doc

### PR DESCRIPTION
**Pull request by shhull**

### CODE REVIEW

**Comment by jichenjc** [comment]
do we want to link to HOST:NODE meaning? where's the value comes from?

**Comment by shhull** [comment]
> do we want to link to HOST:NODE meaning? where's the value comes from?

I've add it in our README about the command line to get those values.
```
| Property | Default | Description | 
| ------ | ------ | ------ |
| `create_server_zone` |''| The zone you can select which host instances are launched on and which roles can boot instances on this host, the value format is `ZONE:HOST:NODE`, HOST and NODE are optional parameters, in such cases, use the `ZONE::NODE`, `ZONE:HOST` or `ZONE`. Default value is '', which means to use the default availability zone. [ ZONE: `openstack availability zone list` HOST: `openstack host list` NODE: `openstack hypervisor list` ]|
```

**Comment by jichenjc** [comment]
@shhull sorry for another ask.. can you help add some info into our own KC and link to here

those are result but I think it's hard for people to know which param to use ..
```
[root@kvmcore11 ~]# openstack host list
+--------------------+-----------+---------------+
| Host Name          | Service   | Zone          |
+--------------------+-----------+---------------+
| kvmcore11          | conductor | internal      |
| kvmcore11          | health    | internal      |
| kvmcore11          | scheduler | internal      |
| kvmcore14.icic.boe | compute   | Default_Group |
+--------------------+-----------+---------------+
[root@kvmcore11 ~]# openstack hypervisor list
+--------------------------------------+---------------------+-----------------+-------------+-------+
| ID                                   | Hypervisor Hostname | Hypervisor Type | Host IP     | State |
+--------------------------------------+---------------------+-----------------+-------------+-------+
| c85d7ebf-7d78-482e-9d94-f5baf303475e | kvmcore14.icic.boe  | QEMU            | 172.26.2.14 | up    |
+--------------------------------------+---------------------+-----------------+-------------+-------+

```

**Comment by shhull** [comment]
> @shhull sorry for another ask.. can you help add some info into our own KC and link to here
> 
> those are result but I think it's hard for people to know which param to use ..
> 
> ```
> [root@kvmcore11 ~]# openstack host list
> +--------------------+-----------+---------------+
> | Host Name          | Service   | Zone          |
> +--------------------+-----------+---------------+
> | kvmcore11          | conductor | internal      |
> | kvmcore11          | health    | internal      |
> | kvmcore11          | scheduler | internal      |
> | kvmcore14.icic.boe | compute   | Default_Group |
> +--------------------+-----------+---------------+
> [root@kvmcore11 ~]# openstack hypervisor list
> +--------------------------------------+---------------------+-----------------+-------------+-------+
> | ID                                   | Hypervisor Hostname | Hypervisor Type | Host IP     | State |
> +--------------------------------------+---------------------+-----------------+-------------+-------+
> | c85d7ebf-7d78-482e-9d94-f5baf303475e | kvmcore14.icic.boe  | QEMU            | 172.26.2.14 | up    |
> +--------------------------------------+---------------------+-----------------+-------------+-------+
> ```

Never mind, thanks for your reviewing carefully. Yes, we should add more details for which column to use. I have update it ( see the below table), what do you think?

| Property | Default | Description | 
| ------ | ------ | ------ |
| `create_server_zone` |''| The zone you can select which host instances are launched on and which roles can boot instances on this host, the value format is `ZONE:HOST:NODE`, HOST and NODE are optional parameters, in such cases, use the `ZONE::NODE`, `ZONE:HOST` or `ZONE`. Default value is '', which means to use the default availability zone. [ **ZONE** is `Zone Name` column from `openstack availability zone list`; **HOST** is `Host Name` column from `openstack host list`; **NODE** is `Hypervisor Hostname` column from `openstack hypervisor list`]|

**Comment by jichenjc** [comment]
ok, we can always optimize this , thanks for the update :)

lgtm

**Pull request merged**
